### ISSUE TITLE
menu card resizing timing on scroll

### ISSUE THREAD

**Issue by susanchapas** [jjjpanda/me#44]
clicking new cards results in weird resizing. animation isn't visually fluid. previous cards expand even when they're not the current selection. currently expanded card has clunky contraction.

**Comment by jjjpanda** [comment]
the only thing i can think of rn is making the animation timing a lot more `ease-in` (may have to use a bezier curve to truly fine tune that)

**Comment by jjjpanda** [comment]
jotting this as an idea for useSectionHeight

append scroll changes to a ledger of active section possibilities

these should be culled such that the consecutive events with the same section key get removed except for the newest

as long as this ledger has more than 1 entry, keep a setInterval going that
every few milliseconds checks the ledger

it takes the most reasonable activekey and takes that
if that happens to be an older one, the ledger is kept intact but the newest entry gets an updated time

if the setInterval takes the newest entry because enough time has elapsed from it and the older entries
the older entries are deleted
breaking the setInterval until new entries come in
